# Generated by Django 6.1 on 2026-08-24 14:13

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=120)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scanning', 'Scanning'), ('in_review', 'In review'), ('complete', 'Complete'), ('failed', 'Failed')], default='scanning', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('confidence_threshold', models.FloatField(default=0.85)),
                ('preset', models.CharField(choices=[('redact', 'Redact'), ('mask', 'Mask'), ('pseudo', 'Pseudonymize'), ('keep', 'Keep')], default='mask', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('page', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('title', 'Title'), ('sub', 'Subtitle'), ('h', 'Heading'), ('p', 'Paragraph')], default='p', max_length=8)),
                ('text', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='documents.job')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('name', 'Name'), ('geo', 'Geographic'), ('date', 'Date'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('ssn', 'SSN'), ('mrn', 'Medical record no.'), ('plan', 'Health plan no.'), ('account', 'Account no.'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('device', 'Device identifier'), ('url', 'URL'), ('ip', 'IP address'), ('biometric', 'Biometric'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('redact', 'Redact'), ('mask', 'Mask'), ('pseudo', 'Pseudonymize'), ('keep', 'Keep')], default='mask', max_length=16)),
                ('token', models.CharField(max_length=40)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='documents.job')),
            ],
        ),
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=8)),
                ('file', models.FileField(upload_to='exports/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_artifacts', to='documents.job')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'format'), name='unique_export_per_job_format')],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('category', models.CharField(choices=[('name', 'Name'), ('geo', 'Geographic'), ('date', 'Date'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('ssn', 'SSN'), ('mrn', 'Medical record no.'), ('plan', 'Health plan no.'), ('account', 'Account no.'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('device', 'Device identifier'), ('url', 'URL'), ('ip', 'IP address'), ('biometric', 'Biometric'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=16)),
                ('value', models.TextField()),
                ('surrogate_value', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('redact', 'Redact'), ('mask', 'Mask'), ('pseudo', 'Pseudonymize'), ('keep', 'Keep')], default='keep', max_length=16)),
                ('confidence', models.FloatField()),
                ('page', models.PositiveIntegerField()),
                ('detector', models.CharField(default='pattern', max_length=16)),
                ('start_in_block', models.PositiveIntegerField()),
                ('end_in_block', models.PositiveIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='documents.documentblock')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='documents.job')),
            ],
            options={
                'ordering': ['block__index', 'start_in_block'],
                'constraints': [models.UniqueConstraint(fields=('job', 'code'), name='unique_entity_code_per_job')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentblock',
            constraint=models.UniqueConstraint(fields=('job', 'index'), name='unique_block_index_per_job'),
        ),
        migrations.AddConstraint(
            model_name='categoryrule',
            constraint=models.UniqueConstraint(fields=('job', 'category'), name='unique_rule_per_job_category'),
        ),
    ]
