# Generated by Django 6.1 on 2026-09-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentblock',
            name='source',
            field=models.CharField(choices=[('text', 'Text layer'), ('ocr', 'OCR')], default='text', max_length=4),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='category',
            field=models.CharField(choices=[('patient_name', 'Patient name'), ('physician_name', 'Physician / provider name'), ('name', 'Other person name'), ('facility', 'Facility / organization'), ('geo', 'Geographic'), ('date', 'Date'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('ssn', 'SSN'), ('mrn', 'Medical record no.'), ('plan', 'Health plan no.'), ('account', 'Account no.'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('device', 'Device identifier'), ('url', 'URL'), ('ip', 'IP address'), ('biometric', 'Biometric'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=16),
        ),
        migrations.AlterField(
            model_name='documentblock',
            name='type',
            field=models.CharField(choices=[('title', 'Title'), ('sub', 'Subtitle'), ('h', 'Heading'), ('p', 'Paragraph'), ('table_row', 'Table row')], default='p', max_length=9),
        ),
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.CharField(choices=[('patient_name', 'Patient name'), ('physician_name', 'Physician / provider name'), ('name', 'Other person name'), ('facility', 'Facility / organization'), ('geo', 'Geographic'), ('date', 'Date'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('ssn', 'SSN'), ('mrn', 'Medical record no.'), ('plan', 'Health plan no.'), ('account', 'Account no.'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('device', 'Device identifier'), ('url', 'URL'), ('ip', 'IP address'), ('biometric', 'Biometric'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=16),
        ),
    ]
