# Generated by Django 6.1 on 2026-09-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentblock_source_alter_categoryrule_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='boxes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('image', models.ImageField(upload_to='page_images/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='documents.job')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('job', 'number'), name='unique_page_per_job')],
            },
        ),
    ]
