# Generated by Django 6.1 on 2026-09-16 08:54

import django.db.models.deletion
from django.db import migrations, models


def distribute_existing_documents(apps, schema_editor):
    """Existing jobs predate the folder system and have no project/patient
    of their own — file them under one placeholder project/patient so the
    library starts from a valid tree instead of a pile of unfiled documents."""
    Folder = apps.get_model("documents", "Folder")
    Job = apps.get_model("documents", "Job")
    if not Job.objects.exists():
        return
    project = Folder.objects.create(name="Unsorted")
    patient = Folder.objects.create(name="Unassigned", parent=project)
    Job.objects.update(folder=patient)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_entity_boxes_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.folder'),
        ),
        migrations.RunPython(distribute_existing_documents, noop),
    ]
