# Generated by Django 6.1 on 2026-09-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_folder_job_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('patient_name', 'Patient name'), ('physician_name', 'Physician / provider name'), ('name', 'Other person name'), ('facility', 'Facility / organization'), ('geo', 'Geographic'), ('date', 'Date'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('ssn', 'SSN'), ('mrn', 'Medical record no.'), ('plan', 'Health plan no.'), ('account', 'Account no.'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('device', 'Device identifier'), ('url', 'URL'), ('ip', 'IP address'), ('biometric', 'Biometric'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('redact', 'Redact'), ('mask', 'Mask'), ('pseudo', 'Pseudonymize'), ('keep', 'Keep')], default='mask', max_length=16)),
                ('token', models.CharField(max_length=40)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='documents.folder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('folder', 'category'), name='unique_rule_per_folder_category')],
            },
        ),
    ]
