# Generated by Django 6.1 on 2026-09-22 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_uploadbatch_job_batch_jobstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrule',
            name='category',
            field=models.CharField(choices=[('patient_name', 'Patient name'), ('physician_name', 'Physician / provider name'), ('person_name', 'Other person name'), ('guarantor_name', 'Guarantor / next of kin'), ('facility_name', 'Facility / organization'), ('employer', 'Employer'), ('date_of_birth', 'Date of birth'), ('date_of_service', 'Date of service'), ('other_date', 'Other date'), ('age_over_89', 'Age above 89'), ('age_89_or_below', 'Age 89 or below'), ('street_address', 'Street address'), ('zip_code', 'ZIP code'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('url', 'URL'), ('ssn', 'SSN / government ID'), ('mrn', 'Medical record number'), ('member_id', 'Member ID'), ('account', 'Account number'), ('payment_card', 'Payment card / bank identifier'), ('ip_address', 'IP address'), ('device_id', 'Device identifier'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('biometric', 'Biometric identifier'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=32),
        ),
        migrations.AlterField(
            model_name='documentblock',
            name='source',
            field=models.CharField(choices=[('text', 'Text layer'), ('tesseract', 'Tesseract OCR'), ('azure_ocr', 'Azure Document Intelligence')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.CharField(choices=[('patient_name', 'Patient name'), ('physician_name', 'Physician / provider name'), ('person_name', 'Other person name'), ('guarantor_name', 'Guarantor / next of kin'), ('facility_name', 'Facility / organization'), ('employer', 'Employer'), ('date_of_birth', 'Date of birth'), ('date_of_service', 'Date of service'), ('other_date', 'Other date'), ('age_over_89', 'Age above 89'), ('age_89_or_below', 'Age 89 or below'), ('street_address', 'Street address'), ('zip_code', 'ZIP code'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('url', 'URL'), ('ssn', 'SSN / government ID'), ('mrn', 'Medical record number'), ('member_id', 'Member ID'), ('account', 'Account number'), ('payment_card', 'Payment card / bank identifier'), ('ip_address', 'IP address'), ('device_id', 'Device identifier'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('biometric', 'Biometric identifier'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=32),
        ),
        migrations.AlterField(
            model_name='entity',
            name='detector',
            field=models.CharField(default='pattern', max_length=32),
        ),
        migrations.AlterField(
            model_name='foldercategoryrule',
            name='category',
            field=models.CharField(choices=[('patient_name', 'Patient name'), ('physician_name', 'Physician / provider name'), ('person_name', 'Other person name'), ('guarantor_name', 'Guarantor / next of kin'), ('facility_name', 'Facility / organization'), ('employer', 'Employer'), ('date_of_birth', 'Date of birth'), ('date_of_service', 'Date of service'), ('other_date', 'Other date'), ('age_over_89', 'Age above 89'), ('age_89_or_below', 'Age 89 or below'), ('street_address', 'Street address'), ('zip_code', 'ZIP code'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('url', 'URL'), ('ssn', 'SSN / government ID'), ('mrn', 'Medical record number'), ('member_id', 'Member ID'), ('account', 'Account number'), ('payment_card', 'Payment card / bank identifier'), ('ip_address', 'IP address'), ('device_id', 'Device identifier'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('biometric', 'Biometric identifier'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('scanning', 'Scanning'), ('in_review', 'In review'), ('finalizing', 'Finalizing'), ('complete', 'Complete'), ('failed', 'Failed')], default='scanning', max_length=16),
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_code', models.CharField(max_length=12)),
                ('category', models.CharField(choices=[('patient_name', 'Patient name'), ('physician_name', 'Physician / provider name'), ('person_name', 'Other person name'), ('guarantor_name', 'Guarantor / next of kin'), ('facility_name', 'Facility / organization'), ('employer', 'Employer'), ('date_of_birth', 'Date of birth'), ('date_of_service', 'Date of service'), ('other_date', 'Other date'), ('age_over_89', 'Age above 89'), ('age_89_or_below', 'Age 89 or below'), ('street_address', 'Street address'), ('zip_code', 'ZIP code'), ('phone', 'Telephone'), ('fax', 'Fax'), ('email', 'Email'), ('url', 'URL'), ('ssn', 'SSN / government ID'), ('mrn', 'Medical record number'), ('member_id', 'Member ID'), ('account', 'Account number'), ('payment_card', 'Payment card / bank identifier'), ('ip_address', 'IP address'), ('device_id', 'Device identifier'), ('license', 'Certificate / licence'), ('vehicle', 'Vehicle identifier'), ('biometric', 'Biometric identifier'), ('photo', 'Full-face image'), ('other', 'Other identifier')], max_length=32)),
                ('value_hash', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('redact', 'Redact'), ('mask', 'Mask'), ('pseudo', 'Pseudonymize'), ('keep', 'Keep')], max_length=16)),
                ('detector', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('page', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='documents.job')),
            ],
            options={
                'ordering': ['entity_code'],
                'constraints': [models.UniqueConstraint(fields=('job', 'entity_code'), name='unique_audit_record_per_job_entity')],
            },
        ),
    ]
