# Generated by Django 6.1 on 2026-09-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_categoryrule_category_and_more"),
        ("documents", "0006_uploadbatch_job_batch_jobstage"),
    ]

    operations = []
