# Generated by Django 6.1 on 2026-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_merge_20260917_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foldercategoryrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("patient_name", "Patient name"),
                    ("physician_name", "Physician / provider name"),
                    ("person_name", "Other person name"),
                    ("guarantor_name", "Guarantor / next of kin"),
                    ("facility_name", "Facility / organization"),
                    ("employer", "Employer"),
                    ("date_of_birth", "Date of birth"),
                    ("date_of_service", "Date of service"),
                    ("other_date", "Other date"),
                    ("age_over_89", "Age above 89"),
                    ("age_89_or_below", "Age 89 or below"),
                    ("street_address", "Street address"),
                    ("zip_code", "ZIP code"),
                    ("phone", "Telephone"),
                    ("fax", "Fax"),
                    ("email", "Email"),
                    ("url", "URL"),
                    ("ssn", "SSN / government ID"),
                    ("mrn", "Medical record number"),
                    ("member_id", "Member ID"),
                    ("account", "Account number"),
                    ("payment_card", "Payment card / bank identifier"),
                    ("ip_address", "IP address"),
                    ("device_id", "Device identifier"),
                    ("license", "Certificate / licence"),
                    ("vehicle", "Vehicle identifier"),
                    ("biometric", "Biometric identifier"),
                    ("photo", "Full-face image"),
                    ("other", "Other identifier"),
                ],
                max_length=16,
            ),
        ),
    ]
