# Generated by hand while resolving the feature/screen-map merge.
#
# 0008_alter_foldercategoryrule_category (main) narrowed this field to
# max_length=16 while independently unifying the category taxonomy; the
# model (documents/models.py) has always declared max_length=32, matching
# every other CharField(choices=CATEGORY_CHOICES) column, so this brings the
# database column back in sync with the model before any new category slug
# longer than 16 characters (several already are, e.g. "age_89_or_below")
# gets silently truncated.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_alter_foldercategoryrule_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foldercategoryrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("patient_name", "Patient name"),
                    ("physician_name", "Physician / provider name"),
                    ("person_name", "Other person name"),
                    ("guarantor_name", "Guarantor / next of kin"),
                    ("facility_name", "Facility / organization"),
                    ("employer", "Employer"),
                    ("date_of_birth", "Date of birth"),
                    ("date_of_service", "Date of service"),
                    ("other_date", "Other date"),
                    ("age_over_89", "Age above 89"),
                    ("age_89_or_below", "Age 89 or below"),
                    ("street_address", "Street address"),
                    ("zip_code", "ZIP code"),
                    ("phone", "Telephone"),
                    ("fax", "Fax"),
                    ("email", "Email"),
                    ("url", "URL"),
                    ("ssn", "SSN / government ID"),
                    ("mrn", "Medical record number"),
                    ("member_id", "Member ID"),
                    ("account", "Account number"),
                    ("payment_card", "Payment card / bank identifier"),
                    ("ip_address", "IP address"),
                    ("device_id", "Device identifier"),
                    ("license", "Certificate / licence"),
                    ("vehicle", "Vehicle identifier"),
                    ("biometric", "Biometric identifier"),
                    ("photo", "Full-face image"),
                    ("other", "Other identifier"),
                ],
                max_length=32,
            ),
        ),
    ]
