# Generated by Django 6.1 on 2026-09-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_foldercategoryrule_category_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='rotation',
            field=models.FloatField(default=0.0),
        ),
    ]
